---
title: "Contoh Random Forest"
author: "Niko Romano / 222011356 / 3SD1"
---


```{r}
library(party)
library(randomForest)
```

# Import Data 

```{r}
# import data
german <- read.csv("D:/Users/ASUS/Documents/Materi Semester 6/Data Mining (DM)/Data/german_credit.csv", header = TRUE)
head(german)
```

```{r}
#jadikan variabel kategorik sebagai faktor
german$Telephone <- as.factor(german$Telephone)
german$ForeignWorker <- as.factor(german$ForeignWorker)
german$Class <- as.factor(german$Class)
```

# Membagi Data 

```{r}
#Partisi data menjadi data training dan testing
library(caret)

#data train sebanyak 75%
inTrain <- createDataPartition(y=german$Class, p=0.75, 
                               list=FALSE)
train <- german[inTrain,]
test <- german[-inTrain,]
```

# Buat Model Random Forest 

```{r}
# buat model random forest.

output.forest <- randomForest(Class ~ ., data = german)
output.forest
importance(output.forest)

varImpPlot(output.forest)
```


# Evaluasi Model 

```{r}
#validasi model dengan data test
Prediksi <- predict(output.forest, test)
```

```{r}
#confusion matrix
CM <- table(test$Class, Prediksi)
CM
```

```{r}
#akurasi
accuracy <- (sum(diag(CM)))/sum(CM)
accuracy
```

```{r}
#load library caret
library(caret)
# definisikan training control
train_control <- trainControl(method="cv", number=10)
```

```{r}
# train the model
model <- train(Class~., data=german, trControl=train_control,
               method="rf")
# summarize results
print(model)
```

# Leave-One-Out 

```{r}
#LEAVE-ONE-OUT
# definisikan training control
train_control <- trainControl(method="LOOCV")
# atur parameter mtry pada random forrest
grid <- expand.grid(.fL=c(0), .usekernel=c(FALSE), .adjust=0.5)
# train the model
model <- train(Class~., data=german, trControl=train_control,
               method="nb", tuneGrid=grid)
# summarize results
print(model)
```

# Bootstrap

```{r}
#BOOTSTRAP
# definisikan training control
train_control <- trainControl(method="boot", number = 100)
# atur parameter mtry pada random forrest
grid <- expand.grid(.fL=c(0), .usekernel=c(FALSE), .adjust=0.5)
# train the model
model <- train(Class~., data=german, trControl=train_control,
               method="nb", tuneGrid=grid)
# summarize results
print(model)
```


```{r}
#PLOT ROC
#data train sebanyak 75%
inTrain <- createDataPartition(y=german$Class, p=0.7, 
                               list=FALSE)
train <- german[inTrain,]
test <- german[-inTrain,]

```

```{r}
# buat model random forest.
output.forest <- randomForest(Class ~ ., data = german)
output.forest
```

```{r}
#prediksi data testing
prediksi <- as.data.frame(predict(output.forest, test,type = "prob"))
prediksi
```


```{r}
#PLOT ROC
#data train sebanyak 75%
inTrain <- createDataPartition(y=german$Class, p=0.75, 
                               list=FALSE)
train <- german[inTrain,]
test <- german[-inTrain,]
```


```{r}
# buat model random forest.
output.forest <- train(Class ~ ., data = german,method="rf")
output.forest
```

```{r}
#prediksi data testing
prediksi <- predict(output.forest, test,type = "prob")
prediksi
```

```{r}
#Plot ROC
library(pROC)
german.roc <- roc(test$Class,prediksi$Bad)
plot.roc(german.roc,print.auc = TRUE)
#to get threshold and accuracy
result.coords <- coords(german.roc, "best",
                        best.method="closest.topleft",
                        ret=c("threshold", "accuracy"))
print(result.coords)
```

```{r}
#Plot ROC2
library(caret)
library(pROC)
data(iris)

# kelas setosa tidak dilibatkan dalam contoh ini
# karena ROC hanya untuk kelas dengan 2 level
iris <- iris[iris$Species == "virginica"|iris$Species == "versicolor", ]
iris$Species <- factor(iris$Species)
```

```{r}
#split data train dan data test
samples <- sample(NROW(iris), NROW(iris) * .5)
data.train <- iris[samples, ]
data.test <- iris[-samples, ]
```

```{r}
#buat model dengan random forrest
forest.model <- train(Species ~., data.train, method="rf")
forest.model
```

```{r}
#prediksi data test
result.predicted.prob <- predict(forest.model, data.test, type="prob") # Prediction
result.predicted.prob
```

```{r}
result.roc <- roc(data.test$Species, result.predicted.prob$versicolor) # Draw ROC curve.
plot(result.roc, print.thres="best", print.thres.best.method="closest.topleft")
#tambahkan smoothed ROC
plot.roc(smooth(result.roc), add=TRUE, col="blue",
         print.auc=TRUE)
#to get threshold and accuracy
result.coords <- coords(result.roc, "best", best.method="closest.topleft", ret=c("threshold", "accuracy"))
print(result.coords)
```









